builds:
  - main: ./cmd/au
    ldflags:
      - -s -w
      - -X github.com/aurelian-one/au/pkg/au.Version={{.Version}}
      - -X github.com/aurelian-one/au/pkg/au.Commit={{.Commit}}
      - -X github.com/aurelian-one/au/pkg/au.CommitTimestamp={{.CommitTimestamp}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: darwin
        goarch: amd64
      - goos: darwin
        goarch: arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  disable: true
