# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v -o au ./cmd/au

    - name: Test
      run: go test -v -race -cover ./...

    - name: Vet
      run: go vet ./...

    - name: Go mod tidy
      run: go mod tidy

    - name: Check diff
      run: git diff --exit-code
