on:
  release:
    types: [created]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
          cache: true
      - run: sudo apt-get -y install gcc-aarch64-linux-gnu
      - uses: goreleaser/goreleaser-action@v2
        with:
          args: release --config .goreleaser-for-linux.yaml ${{ github.event_name == 'pull_request' && '--skip-publish' || '' }}
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release-darwin-binary:
    if: ${{ github.event_name == 'release' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
          cache: true
      - uses: goreleaser/goreleaser-action@v2
        with:
          args: release --config .goreleaser-for-darwin.yaml ${{ github.event_name == 'pull_request' && '--skip-publish' || '' }}
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
